# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tomichi/ClionProjects/semestralka

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tomichi/ClionProjects/semestralka

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tomichi/ClionProjects/semestralka/CMakeFiles /Users/tomichi/ClionProjects/semestralka/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tomichi/ClionProjects/semestralka/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named semestralka

# Build rule for target.
semestralka: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 semestralka
.PHONY : semestralka

# fast build rule for target.
semestralka/fast:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/build
.PHONY : semestralka/fast

BookingCalendar.o: BookingCalendar.cpp.o

.PHONY : BookingCalendar.o

# target to build an object file
BookingCalendar.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/BookingCalendar.cpp.o
.PHONY : BookingCalendar.cpp.o

BookingCalendar.i: BookingCalendar.cpp.i

.PHONY : BookingCalendar.i

# target to preprocess a source file
BookingCalendar.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/BookingCalendar.cpp.i
.PHONY : BookingCalendar.cpp.i

BookingCalendar.s: BookingCalendar.cpp.s

.PHONY : BookingCalendar.s

# target to generate assembly for a file
BookingCalendar.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/BookingCalendar.cpp.s
.PHONY : BookingCalendar.cpp.s

CSVLoader.o: CSVLoader.cpp.o

.PHONY : CSVLoader.o

# target to build an object file
CSVLoader.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/CSVLoader.cpp.o
.PHONY : CSVLoader.cpp.o

CSVLoader.i: CSVLoader.cpp.i

.PHONY : CSVLoader.i

# target to preprocess a source file
CSVLoader.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/CSVLoader.cpp.i
.PHONY : CSVLoader.cpp.i

CSVLoader.s: CSVLoader.cpp.s

.PHONY : CSVLoader.s

# target to generate assembly for a file
CSVLoader.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/CSVLoader.cpp.s
.PHONY : CSVLoader.cpp.s

DateValidator.o: DateValidator.cpp.o

.PHONY : DateValidator.o

# target to build an object file
DateValidator.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DateValidator.cpp.o
.PHONY : DateValidator.cpp.o

DateValidator.i: DateValidator.cpp.i

.PHONY : DateValidator.i

# target to preprocess a source file
DateValidator.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DateValidator.cpp.i
.PHONY : DateValidator.cpp.i

DateValidator.s: DateValidator.cpp.s

.PHONY : DateValidator.s

# target to generate assembly for a file
DateValidator.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DateValidator.cpp.s
.PHONY : DateValidator.cpp.s

DateValidatorException.o: DateValidatorException.cpp.o

.PHONY : DateValidatorException.o

# target to build an object file
DateValidatorException.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DateValidatorException.cpp.o
.PHONY : DateValidatorException.cpp.o

DateValidatorException.i: DateValidatorException.cpp.i

.PHONY : DateValidatorException.i

# target to preprocess a source file
DateValidatorException.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DateValidatorException.cpp.i
.PHONY : DateValidatorException.cpp.i

DateValidatorException.s: DateValidatorException.cpp.s

.PHONY : DateValidatorException.s

# target to generate assembly for a file
DateValidatorException.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DateValidatorException.cpp.s
.PHONY : DateValidatorException.cpp.s

DayReservation.o: DayReservation.cpp.o

.PHONY : DayReservation.o

# target to build an object file
DayReservation.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DayReservation.cpp.o
.PHONY : DayReservation.cpp.o

DayReservation.i: DayReservation.cpp.i

.PHONY : DayReservation.i

# target to preprocess a source file
DayReservation.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DayReservation.cpp.i
.PHONY : DayReservation.cpp.i

DayReservation.s: DayReservation.cpp.s

.PHONY : DayReservation.s

# target to generate assembly for a file
DayReservation.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DayReservation.cpp.s
.PHONY : DayReservation.cpp.s

DayReservationException.o: DayReservationException.cpp.o

.PHONY : DayReservationException.o

# target to build an object file
DayReservationException.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DayReservationException.cpp.o
.PHONY : DayReservationException.cpp.o

DayReservationException.i: DayReservationException.cpp.i

.PHONY : DayReservationException.i

# target to preprocess a source file
DayReservationException.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DayReservationException.cpp.i
.PHONY : DayReservationException.cpp.i

DayReservationException.s: DayReservationException.cpp.s

.PHONY : DayReservationException.s

# target to generate assembly for a file
DayReservationException.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/DayReservationException.cpp.s
.PHONY : DayReservationException.cpp.s

Hotel.o: Hotel.cpp.o

.PHONY : Hotel.o

# target to build an object file
Hotel.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Hotel.cpp.o
.PHONY : Hotel.cpp.o

Hotel.i: Hotel.cpp.i

.PHONY : Hotel.i

# target to preprocess a source file
Hotel.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Hotel.cpp.i
.PHONY : Hotel.cpp.i

Hotel.s: Hotel.cpp.s

.PHONY : Hotel.s

# target to generate assembly for a file
Hotel.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Hotel.cpp.s
.PHONY : Hotel.cpp.s

HotelValidatorException.o: HotelValidatorException.cpp.o

.PHONY : HotelValidatorException.o

# target to build an object file
HotelValidatorException.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/HotelValidatorException.cpp.o
.PHONY : HotelValidatorException.cpp.o

HotelValidatorException.i: HotelValidatorException.cpp.i

.PHONY : HotelValidatorException.i

# target to preprocess a source file
HotelValidatorException.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/HotelValidatorException.cpp.i
.PHONY : HotelValidatorException.cpp.i

HotelValidatorException.s: HotelValidatorException.cpp.s

.PHONY : HotelValidatorException.s

# target to generate assembly for a file
HotelValidatorException.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/HotelValidatorException.cpp.s
.PHONY : HotelValidatorException.cpp.s

HtmlExport.o: HtmlExport.cpp.o

.PHONY : HtmlExport.o

# target to build an object file
HtmlExport.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/HtmlExport.cpp.o
.PHONY : HtmlExport.cpp.o

HtmlExport.i: HtmlExport.cpp.i

.PHONY : HtmlExport.i

# target to preprocess a source file
HtmlExport.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/HtmlExport.cpp.i
.PHONY : HtmlExport.cpp.i

HtmlExport.s: HtmlExport.cpp.s

.PHONY : HtmlExport.s

# target to generate assembly for a file
HtmlExport.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/HtmlExport.cpp.s
.PHONY : HtmlExport.cpp.s

Month.o: Month.cpp.o

.PHONY : Month.o

# target to build an object file
Month.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Month.cpp.o
.PHONY : Month.cpp.o

Month.i: Month.cpp.i

.PHONY : Month.i

# target to preprocess a source file
Month.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Month.cpp.i
.PHONY : Month.cpp.i

Month.s: Month.cpp.s

.PHONY : Month.s

# target to generate assembly for a file
Month.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Month.cpp.s
.PHONY : Month.cpp.s

Room.o: Room.cpp.o

.PHONY : Room.o

# target to build an object file
Room.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Room.cpp.o
.PHONY : Room.cpp.o

Room.i: Room.cpp.i

.PHONY : Room.i

# target to preprocess a source file
Room.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Room.cpp.i
.PHONY : Room.cpp.i

Room.s: Room.cpp.s

.PHONY : Room.s

# target to generate assembly for a file
Room.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Room.cpp.s
.PHONY : Room.cpp.s

RoomValidator.o: RoomValidator.cpp.o

.PHONY : RoomValidator.o

# target to build an object file
RoomValidator.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/RoomValidator.cpp.o
.PHONY : RoomValidator.cpp.o

RoomValidator.i: RoomValidator.cpp.i

.PHONY : RoomValidator.i

# target to preprocess a source file
RoomValidator.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/RoomValidator.cpp.i
.PHONY : RoomValidator.cpp.i

RoomValidator.s: RoomValidator.cpp.s

.PHONY : RoomValidator.s

# target to generate assembly for a file
RoomValidator.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/RoomValidator.cpp.s
.PHONY : RoomValidator.cpp.s

RoomValidatorException.o: RoomValidatorException.cpp.o

.PHONY : RoomValidatorException.o

# target to build an object file
RoomValidatorException.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/RoomValidatorException.cpp.o
.PHONY : RoomValidatorException.cpp.o

RoomValidatorException.i: RoomValidatorException.cpp.i

.PHONY : RoomValidatorException.i

# target to preprocess a source file
RoomValidatorException.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/RoomValidatorException.cpp.i
.PHONY : RoomValidatorException.cpp.i

RoomValidatorException.s: RoomValidatorException.cpp.s

.PHONY : RoomValidatorException.s

# target to generate assembly for a file
RoomValidatorException.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/RoomValidatorException.cpp.s
.PHONY : RoomValidatorException.cpp.s

Year.o: Year.cpp.o

.PHONY : Year.o

# target to build an object file
Year.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Year.cpp.o
.PHONY : Year.cpp.o

Year.i: Year.cpp.i

.PHONY : Year.i

# target to preprocess a source file
Year.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Year.cpp.i
.PHONY : Year.cpp.i

Year.s: Year.cpp.s

.PHONY : Year.s

# target to generate assembly for a file
Year.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/Year.cpp.s
.PHONY : Year.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/semestralka.dir/build.make CMakeFiles/semestralka.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... semestralka"
	@echo "... BookingCalendar.o"
	@echo "... BookingCalendar.i"
	@echo "... BookingCalendar.s"
	@echo "... CSVLoader.o"
	@echo "... CSVLoader.i"
	@echo "... CSVLoader.s"
	@echo "... DateValidator.o"
	@echo "... DateValidator.i"
	@echo "... DateValidator.s"
	@echo "... DateValidatorException.o"
	@echo "... DateValidatorException.i"
	@echo "... DateValidatorException.s"
	@echo "... DayReservation.o"
	@echo "... DayReservation.i"
	@echo "... DayReservation.s"
	@echo "... DayReservationException.o"
	@echo "... DayReservationException.i"
	@echo "... DayReservationException.s"
	@echo "... Hotel.o"
	@echo "... Hotel.i"
	@echo "... Hotel.s"
	@echo "... HotelValidatorException.o"
	@echo "... HotelValidatorException.i"
	@echo "... HotelValidatorException.s"
	@echo "... HtmlExport.o"
	@echo "... HtmlExport.i"
	@echo "... HtmlExport.s"
	@echo "... Month.o"
	@echo "... Month.i"
	@echo "... Month.s"
	@echo "... Room.o"
	@echo "... Room.i"
	@echo "... Room.s"
	@echo "... RoomValidator.o"
	@echo "... RoomValidator.i"
	@echo "... RoomValidator.s"
	@echo "... RoomValidatorException.o"
	@echo "... RoomValidatorException.i"
	@echo "... RoomValidatorException.s"
	@echo "... Year.o"
	@echo "... Year.i"
	@echo "... Year.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

